//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Single InteractWorld
        {
            get
            {
                return SteamVR_Actions.default_InteractWorld;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveForward
        {
            get
            {
                return SteamVR_Actions.default_MoveForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveLeft
        {
            get
            {
                return SteamVR_Actions.default_MoveLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveRight
        {
            get
            {
                return SteamVR_Actions.default_MoveRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveBackwards
        {
            get
            {
                return SteamVR_Actions.default_MoveBackwards;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftHandPose
        {
            get
            {
                return SteamVR_Actions.default_LeftHandPose;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHandPose
        {
            get
            {
                return SteamVR_Actions.default_RightHandPose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
